### ISSUE TITLE
Filtering Slides

### ISSUE THREAD

**Issue by digi4care** [vadimkorr/svelte-carousel#105]
HI i love your Carousel. 
Is there a way we can filter the slides?
In a other webproject i also use a slider for the filterbar (based on slick slider).
We would love to use your carousel because we want to switch too  plain javascript.

Maybe an example will explain more then i did. 
https://codepen.io/Digi4Care/pen/MWoJBQp

**Comment by vadimkorr** [comment]
Hi, thank you!
I think this one should work
So, you have some array and it is changed (by filtering). And you have to wrap the carousel inside `key`, like this:

```
let items = [1, 2, 3, 4, 5];

const handleClick = () => {
  items = items.filter(item => item > 3)
}
```

```
{#key items}
  <Carousel>
    {#each items as item}
      <li>{item}</li>
    {/each}
  </Carousel>
{/key}
```

**Comment by digi4care** [comment]
Thanks. this really helps

**Comment by digi4care** [comment]
It seems that the clickhandler doesnt work on the cloned objects. I have to set "infinte" prop to false

**Comment by digi4care** [comment]
Ah sorry problem already known #91
