### ISSUE TITLE
simply-reactive is missing

### ISSUE THREAD

**Issue by len0xx** [vadimkorr/svelte-carousel#118]
Seems like the package `"simply-reactive"` is deleted from `npmjs.com`, but `svelte-carousel` depends on it. At first running `npm install` gave me errors telling that there is no such package as `simply-reactive` on github. But now I think someone figured it out that it was a problem and `npm install` no longer throws an error. But I'm curious what will happen next? I feel like some day we'll have problems with it again

**Comment by len0xx** [comment]
Are there gonna be any fixes to the problem?

**Comment by vadimkorr** [comment]
Fixed in `svelte-carousel@1.0.23`
