### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by TheoGegout** [vadimkorr/svelte-carousel#119]
Hi !

I followed the readme to install the library and set up the carousel but I have a problem when importing the component.
![image](https://user-images.githubusercontent.com/55431060/196952560-52a749c1-a0ea-42b6-84ab-29fff25ccb09.png)

**Comment by irosadie** [comment]
hei i have same issues=d, how to solve it, thankyou before

**Comment by TheoGegout** [comment]
Hi ! 
Apparently, this is wokring ;)
https://github.com/vadimkorr/svelte-carousel/issues/27
