### ISSUE TITLE
Doesn't work in new sveltekit

### ISSUE THREAD

**Issue by JeffWScott** [vadimkorr/svelte-carousel#122]
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/4855017/200141800-56e427e0-b9e8-453b-9294-b07a5c03ee6f.png">

Followed instructions for svelte kit install. Which are also out of date because kit.vite is no longer a config option.

**Comment by Dhirajraje** [comment]
Same problem. Any luck?

**Comment by oetiker** [comment]
what works is this:

```ts
  let Carousel: ConstructorOfATypedSvelteComponent; // for saving Carousel component class
  onMount(async () => {
    const module = await import('svelte-carousel');
    Carousel = module.default;
  });
  ```
  
  and then later
  
  ```html
    {#if browser}
    <svelte:component
      this={Carousel}
      autoplay
      autoplayDuration={4000}
      duration={500}
      dots={true}
      arrows={false}
    >
      ...
    </svelte:component>
```

**Comment by aunumever** [comment]
The error for the missing `type: module`
`svelte-carousel doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.`

**Comment by Metro13** [comment]
I can work on this issue

**Comment by HoseokYoo** [comment]
> what works is this:
> 
> ```ts
>   let Carousel: ConstructorOfATypedSvelteComponent; // for saving Carousel component class
>   onMount(async () => {
>     const module = await import('svelte-carousel');
>     Carousel = module.default;
>   });
> ```
> 
> and then later
> 
> ```
>   {#if browser}
>   <svelte:component
>     this={Carousel}
>     autoplay
>     autoplayDuration={4000}
>     duration={500}
>     dots={true}
>     arrows={false}
>   >
>     ...
>   </svelte:component>
>   {/if}
> ```
> 
> but obviously it would be great if the component were working without tricks

it's works thank you

**Comment by vadimkorr** [comment]
Should be fixed in https://github.com/vadimkorr/svelte-carousel/pull/126
