### ISSUE TITLE
Will not even install

### ISSUE THREAD

**Issue by SteveC00k** [vadimkorr/svelte-carousel#124]
I am getting errors when trying to install:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

and on digital ocean I get:
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/vadimkorr/simply-reactive.git
npm ERR! Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

I am able to install other repositories without any problems.

**Comment by vadimkorr** [comment]
Duplicates #118
