### ISSUE TITLE
Unknown file extension error on initial page load of svelte-kit site

### ISSUE THREAD

**Issue by michael-farwell** [vadimkorr/svelte-carousel#127]
Upon initial page load of built app, I get the following error: Unknown file extension ".svelte" for **/node_modules/.pnpm/svelte-carousel@1.0.21/node_modules/svelte-carousel/src/components/Carousel/Carousel.svelte

After researching, I was able to figure out that the issue is that the package.json is missing the "svelte" field. This should point to the same place that "main" and "module" are pointing to.

### package.json
```
{
  "name": "svelte-carousel",
  "version": "1.0.21",
  "description": "Svelte carousel",
  "main": "src/main.js",
  "module": "src/main.js",
  "svelte": "src/main.js" <--
  ...
}
```

I did test this locally and it appeared to have worked perfectly. Could this change be implement please?

Also, fantastic library!!

**Comment by oetiker** [comment]
tested it too, works. PR #128

**Comment by vadimkorr** [comment]
merged, thank you
