### ISSUE TITLE
Particle Grid feature

### ISSUE THREAD

**Issue by dtsmarin** [vadimkorr/svelte-carousel#135]
Very nice component! I'd like to create a carousel with a grid instead of a single line of Particles.

Something like this would be great:
particlesToShow=50
particlesToScroll=50
particlesRows=10
particlesColumns=5

**Comment by vadimkorr** [comment]
Thank you!
You can apply this grid inside the page manually, like this

```html
<Carousel
  bind:this={carousel}
>
  <div class="grid">
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
    <div class="grid-item"></div>
  </div>
  <div class="grid"></div>
  <div class="grid"></div>
</Carousel>
```
