### ISSUE TITLE
Get active carousel page from another component

### ISSUE THREAD

**Issue by elzdave** [vadimkorr/svelte-carousel#17]
Hello, recently used your nice package and it seems to fit my needs. However, I needs to get current page index to sync with another components, so when the page is displayed, the other component should react to that updates. Searching through your code and still have no clue about it. Is there any possibilities to get the current page index, or maybe listening to event handling the changes? Thanks in advance.

**Comment by vadimkorr** [comment]
Hello, thank you!
Is it ok for you if I add this event?

```jsx
<Carousel
  on:pageChange={event => console.log(`Current page index: ${event.detail}`)}
>
  // ...
</Carousel>
```

**Comment by elzdave** [comment]
Wow, that's was exactly what I need. Thank you for this nice support and I'm waiting for the release :)

**Comment by vadimkorr** [comment]
@elzdave, released, version 1.0.2

**Comment by elzdave** [comment]
Allright, updating my deps right now! Have a nice day 😎

**Comment by vadimkorr** [comment]
Thanks! Have a good day! 🙂
