### ISSUE TITLE
Swipe Support

### ISSUE THREAD

**Issue by tonprince** [vadimkorr/svelte-carousel#28]
Is there any swipe support for sliding the content?

**Comment by vadimkorr** [comment]
Hi @tonprince,
yes, it should work out of the box, but there is no support for safari yet.

**Comment by tonprince** [comment]
When using sveltekit with swiper I have the following issues as described in the minimal sample project:
https://github.com/tonprince/sveltekit-swiper

**Comment by vadimkorr** [comment]
The official workaround is:
1. Install it as a dev dependency:
`npm install svelte-carousel -D`

2. Import it like this: 
```
<script>
  import { onMount } from 'svelte';

  let Carousel;
  onMount(async () => {
    const module = await import('svelte-carousel');
    Carousel = module.default;
  });
</script>

<svelte:component this={Carousel}>
  <div>1</div>
  <div>2</div>
  <div>3</div>
</svelte:component>
```


[How do I use a client-side only library that depends on document or window?](https://kit.svelte.dev/faq)
[why -D ?](https://github.com/sveltejs/sapper-template#using-external-components)

**Comment by vadimkorr** [comment]
Swipe works with SvelteKit as well, you just need to import the package differently:
https://github.com/vadimkorr/svelte-carousel/issues/27#issuecomment-851022295
