### ISSUE TITLE
Carousel styling customization

### ISSUE THREAD

**Issue by rodrigopineda028** [vadimkorr/svelte-carousel#30]
I have a question on this great library. Is it intended to add styling customization options for the Carousel container in the future (not just the arrows and dot buttons)?

If not, is it legit to assume the class names ```.sc-carousel__carousel-container``` and ```.sc-carousel__content-container``` won't change?

Thanks in advance!

**Comment by vadimkorr** [comment]
Hi @rodrigopineda028,
Thank you 🙂 
You can use `.sc-carousel__*` class name for customization. There will no breaking changes in minor versions.
I'll keep that in mind.

**Comment by EssamWisam** [comment]
Be good to expose this in the documentation. Was going crazy when I found no mention of styling or CSS.
