### ISSUE TITLE
Show pause indicator when autoplay is paused on focus

### ISSUE THREAD

**Issue by weaseldotro** [vadimkorr/svelte-carousel#31]
When `pauseOnFocus` is true and the carousel is paused, a visual indicator should be shown on the carousel. Maybe a pause icon or text or something, but I think it would be best if a slot would be used, so the user can add whatever they want.

**Comment by vadimkorr** [comment]
Hi @weaseldotro,
Nice idea, ok

**Comment by vadimkorr** [comment]
@weaseldotro could you please send a sketch or smth visual of
how do you want this pause indicator should look like, and
where exactly in the carousel?

**Comment by weaseldotro** [comment]
Hmm, how about a 2px or 3px progress bar at the top or at the bottom of the image that will start at 100% and then decrease according to the duration? https://css-tricks.com/timer-bars-in-css-with-custom-properties/

When the mouse is hovered on the image, the progress bar should pause.
On mobile, when the user taps the image the progress bar shoud pause, and the on the second tap it should resume.

I think this is the best solution.

**Comment by vadimkorr** [comment]
Released in `svelte-carousel@1.0.10`

**Comment by weaseldotro** [comment]
Looks great, good job!

I've noticed a little quirk: on my iPhone with Safari, tapping on a carousel with autoplay with pause on focus will restart the current progress from zero. However, there is noticeable delay between the time you tap on the image and the restart of the progress. Not a lot, I'm guessing something like .5 seconds, but still, pretty noticeable.

Also, I think my initial suggestion would work better on mobile than the current implementation: when the user taps the image the progress bar should pause, and then on the second tap it should resume.

**Comment by vadimkorr** [comment]
Yes, it is initial solution for focusing behaviour, which comes from one of the previous releases. Seems it works differently in Safari. I'll rethink it with two-taps-approach as well.
Thanks.
