### ISSUE TITLE
changing current page externally

### ISSUE THREAD

**Issue by PeterHuefner** [vadimkorr/svelte-carousel#33]
Is there any possibility of changing the current page from outside the component?
The showPage-function is not exported for external calling.

Use case could be clicking a button somewhere (not the arrows or dots inside) and to switch to a specific page.
It would be cool when bind to the currentPageIndex (or similiar) and by changing it anywhere the carousel updates itself.

Or is that anyhow possible, but I am not seeing it?
Thanks for help or ideas.

**Comment by vadimkorr** [comment]
Hello @PeterHuefner ,
There is no offical way to change page programmatically yet,
but I will add this functionality in the upcoming releases.
Thanks!

**Comment by vadimkorr** [comment]
Hello @PeterHuefner , 
released in `svelte-carousel@1.0.9`

**Comment by PeterHuefner** [comment]
Thank you Vadim!
