### ISSUE TITLE
Carousel's 'current index page' is set to initial page when resizing window

### ISSUE THREAD

**Issue by rodrigopineda028** [vadimkorr/svelte-carousel#34]
I noticed this behavior, I was wondering if there's a reason for changing the currentIndexPage to initialPageIndex when resizing the browser's window? Can it be solved by removing the line of the code where it sets the index page on ` applyPageSizes `  ?

Thanks again for your help and this awesome tool.

**Comment by vadimkorr** [comment]
Ok, I will take a look
Thanks!

**Comment by vadimkorr** [comment]
Hello @rodrigopineda028,
released

**Comment by rodrigopineda028** [comment]
Awesome!
Thank you, have a good one!
