### ISSUE TITLE
Disable dragging the slides using mouse or touch (swipe)

### ISSUE THREAD

**Issue by weaseldotro** [vadimkorr/svelte-carousel#47]
Hi, great work so far, I really love what you did with this component.

I think it would be great if you could disable the ability to drag the carousel's slides using the mouse or swipe (when on mobile). Maybe add a boolean prop called `swiping` that default to `true` but can be changed by the developer.

As a side notice, on my phone the carousel is *extremely* sensitive when I touch it. For example if I want to just scroll the page downwards and I swipe up on the carousel, the page does indeed scroll downwards but the carousel also swipes left or right almost immediately, even though I barely moved my finger.

**Comment by vadimkorr** [comment]
Thank you so much!
Ok, will do.
