### ISSUE TITLE
 SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by prakashUXtech** [vadimkorr/svelte-carousel#60]
getting this error while using with svelte kit ..

**Comment by vadimkorr** [comment]
Hi @prakashUXtech, please try this approach https://github.com/vadimkorr/svelte-carousel/issues/27#issuecomment-851022295

**Comment by vadimkorr** [comment]
Extended readme https://github.com/vadimkorr/svelte-carousel#sveltekit-support
