### ISSUE TITLE
Is there any way to show some part of next element?

### ISSUE THREAD

**Issue by niwasmala** [vadimkorr/svelte-carousel#67]
Hello. Thanks for creating svelte carousel.

I want to ask, is there any way display some partof next element? Sorry if my question is unclear.

Here is the example I want to achieve.

![image](https://user-images.githubusercontent.com/476869/131248252-9cdb5fa5-06fc-41f8-b0c2-cb81307fd800.png)

I don't find how to set how many elements to display, e.g. `perView` in GlideJS or `slidesToShow` in Slick Carousel. I use slick carousel in previous and set slidesToShow to 1.2 to display 20% of next element.

When I use svelte-carousel, it only display exact 1 element. 

![image](https://user-images.githubusercontent.com/476869/131247686-3739c737-dbb9-4539-a591-015834841019.png)

It would be great if svelte-carousel do this!

**Comment by vadimkorr** [comment]
Hello @niwasmala,
Thank you!
There is no ready-to-use way to achieve it yet, but I think you can play with customizing css styles which start with `sc-`.

**Comment by ziso** [comment]
@niwasmala did you get this to work for you? if so can you please share a solution?
also I must agree, this is a great component, thanks for that @vadimkorr
