### ISSUE TITLE
Carousel on page load 

### ISSUE THREAD

**Issue by TheGuyInApt42** [vadimkorr/svelte-carousel#68]
Thanks for your work! I have an issue where if the carousel is on autoplay, it takes a second or two to load on the page. Is there a way to check if carousel is loaded so i can do something like if carousel is loaded, just display, else display the first image or some sort of loading indicator. I am not sure if I missed something but i believe I went through all of the props and options.

**Comment by vadimkorr** [comment]
Hi @TheGuyInApt42,
Thank you! Does it happen with SvelteKit?
There is no any 'loaded' event actually. What if to wrap carousel and then use onMount hook of the wrapper (and if it is SvelteKit, wrapper should be imported the same way as carousel)

**Comment by TheGuyInApt42** [comment]
Thanks for the quick response! Yes I am using SvelteKit and using the workaround. 

<svelte:component
  this={Carousel}
  bind:this={carousel} 
  autoplay
  autoplayDuration={5000}
  autoplayProgressVisible
  
>
    {#each images as image}
        <div class="slide-image">
            <img src={image} alt="">
        </div>
    {/each}

</svelte:component>


You're saying wrap the carousel in a module and then use onMount on that wrapper to control the state of carousel?

**Comment by vadimkorr** [comment]
Yes, kind of.
The idea is that onMount of the wrapper may tell that carousel is loaded. If it will not work, I will add some event or smth like that

**Comment by TheGuyInApt42** [comment]
Thanks for your suggestion, I fixed that issue. A slight issue I have now is I have a sticky header that displays behind the carousel when scrolling. I was thinking it might be a z-index issue, do you have any suggestions so that the header will display over the carousel. Thanks again

**Comment by vadimkorr** [comment]
There should be some parent element with `position: relative`, and you can put sticky header as a child element there with `position: absolute` and top:0,left:0, right:0. Smth like that.

**Comment by TheGuyInApt42** [comment]
i got it, thanks

**Comment by vadimkorr** [comment]
Cool, thanks!
