### ISSUE TITLE
The next slide protrudes into the current slide.

### ISSUE THREAD

**Issue by mweissen** [vadimkorr/svelte-carousel#71]
Google Chrome:
At certain widths of the window, a narrow part of the next slide is displayed. Width probably 1px. Possibly the cause is a rounding error in the calculation of the width.

Reproduction: 
(1) Fill slides with different background colors.
(2) Call a svelte-carousel website with Google Chrome.
(3) Change width of window slowly. At certain widths, a narrow strip of the next page is visible.

The problem does not occur in Opera, Microsoft Edge or Firefox.

The attached picture shows a part of a screenshot. The narrow green part on the right side is part of the next page with background-color:green .

![slide 1](https://user-images.githubusercontent.com/1044433/132133552-af58ca12-fca4-4d29-b49d-e19510defe0a.png)

**Comment by vadimkorr** [comment]
In 1.0.16, the bug does not reproduce

**Comment by mweissen** [comment]
Thank you very much! I just tried the program again and the error is no longer there.
