### ISSUE TITLE
Item's width are not 100% on first load

### ISSUE THREAD

**Issue by dylancl** [vadimkorr/svelte-carousel#73]
Hi

I'm using svelte-carousel to display images in a modal, using SvelteKit. Everything works fine, but when I first open a modal containing a carousel, the width of the images is not 100% of the parent's width, even though I explicitly set it like that.

The result of it looks like this: ![image](https://user-images.githubusercontent.com/14956708/132950660-a2c36683-5f2b-4d44-a07a-581de7a6ff3d.png).

However, when I close the first modal, and then re-open it, the new carousel works fine (respects the width I set) and so does every carousel after that. 

After re-opening the modal containing the carousel, it does work how I expect it to looking like this:
![image](https://shibe.host/FXFdDuVUzsUD/direct) 

From looking at the CSS rules with Inspector, I noticed that it might have to do with the `min-width` it sets on the images, but when using `min-width: 100% !important` the different carousel items start overflowing like so: ![image](https://shibe.host/u6FGjYcbEInu/direct)

I'm not sure what's causing this after trying to debug it for a couple of hours, so that's why I figured I'd try asking here.

Thanks!

**Comment by vadimkorr** [comment]
Hi,
Changed the way of applying the width. Please try to install `svelte-carousel@1.0.15-rc1`

**Comment by dylancl** [comment]
Thanks for much for the quick commit, amazing to see!

After installing `svelte-carousel@1.0.15-rc1` the issue is completely fixed.

Thanks a lot for the help, as well as the amazing package.

**Comment by vadimkorr** [comment]
Cool, thank you!
