### ISSUE TITLE
Remove Dots and arrows 

### ISSUE THREAD

**Issue by TheArctesian** [vadimkorr/svelte-carousel#83]
I want to get rid of the arrows and dots underneath so I can just have the scrolling images but every time I delete from the bundle.css it comes back on reload. Could anyone help me find out how to do this without having to delete a bunch of code everytime.

**Comment by vadimkorr** [comment]
Hi @TheArctesian, 
Just use props like this:
```
<Carousel
  arrows={false}
  dots={false}
></Carousel>
```

**Comment by TheArctesian** [comment]
thanks is there any documentation for this I can read more on

**Comment by vadimkorr** [comment]
Sure,
here https://github.com/vadimkorr/svelte-carousel
and here https://vadimkorr.github.io/svelte-carousel/
