### ISSUE TITLE
The requested module does not provide an export named 'default

### ISSUE THREAD

**Issue by justingolden21** [vadimkorr/svelte-carousel#85]
When I import it:

`import Carousel from 'svelte-carousel'`

I get:

`The requested module '/node_modules/lodash.isequal/index.js?v=4248d81f' does not provide an export named 'default'`

I have lodash merge:

`lodash.merge": "^4.6.2",`

as a dependency for what it's worth...

**Comment by justingolden21** [comment]
deleted all folders and modules and reinstalled and ran dev and I get:
<details>
<summary>output</summary>
```cmd
11:31:23 PM [vite] Error when evaluating SSR module /node_modules/lodash.get/index.js?v=930b6405:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=930b6405:931:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-92cbd8f1.js:66520:15)
11:31:23 PM [vite] Error when evaluating SSR module /node_modules/simply-reactive/src/simply-reactive.js:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=930b6405:929:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-92cbd8f1.js:66520:15)
11:31:23 PM [vite] Error when evaluating SSR module /node_modules/simply-reactive/main.js:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=930b6405:927:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-92cbd8f1.js:66520:15)
11:31:23 PM [vite] Error when evaluating SSR module /node_modules/svelte-carousel/src/components/Carousel/createCarousel.js:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=930b6405:925:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-92cbd8f1.js:66520:15)
11:31:23 PM [vite] Error when evaluating SSR module /node_modules/svelte-carousel/src/components/Carousel/Carousel.svelte:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=930b6405:923:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-92cbd8f1.js:66520:15)
11:31:23 PM [vite] Error when evaluating SSR module /node_modules/svelte-carousel/src/main.js?v=930b6405:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=930b6405:921:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-92cbd8f1.js:66520:15)
11:31:23 PM [vite] Error when evaluating SSR module /src/routes/index.svelte:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=930b6405:919:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-92cbd8f1.js:66520:15)
module is not defined
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=930b6405:917:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-92cbd8f1.js:66520:15)
```
</details>

**Comment by justingolden21** [comment]
Got rid of lodash from my project and still encounter the same problem

Also this package has one dependency and it's a 404 on npmjs.com

https://www.npmjs.com/package/svelte-carousel

https://www.npmjs.com/package/simply-reactive

**Comment by justingolden21** [comment]
here your package.json has:

```json
"devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/plugin-transform-runtime": "^7.14.5",
    "@babel/preset-env": "^7.12.11",
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-image": "^2.1.0",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^11.0.0",
    "@storybook/addon-actions": "^6.1.14",
    "@storybook/addon-essentials": "^6.1.14",
    "@storybook/addon-links": "^6.1.14",
    "@storybook/svelte": "^6.1.14",
    "babel-loader": "^8.2.2",
    "jest": "^26.6.3",
    "lodash": "^4.17.20",
    "mdsvex": "^0.8.9",
    "rollup": "^2.3.4",
    "rollup-plugin-babel": "^4.4.0",
    "rollup-plugin-import-css": "^2.0.1",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "sirv-cli": "^1.0.11",
    "svelte": "^3.31.2",
    "svelte-loader": "^2.13.6"
  },
  "dependencies": {
    "simply-reactive": "vadimkorr/simply-reactive#1.0.0"
  }
```

but on my machine after cloning just minutes ago I have 
```json
"devDependencies": {
    "@babel/cli": "^7.15.7",
    "@babel/core": "^7.15.8",
    "@babel/preset-env": "^7.15.8",
    "babel-jest": "^27.2.5",
    "jest": "^27.2.5"
  },
  "dependencies": {
    "lodash.clonedeep": "^4.5.0",
    "lodash.get": "^4.4.2",
    "lodash.isequal": "^4.5.0"
  }
```

**Comment by vadimkorr** [comment]
Hi @justingolden21, I'll take a look.
yes, simply-reactive is not an npm package, it is installed right from github, it's fine.

**Comment by justingolden21** [comment]
Thanks for taking a look.

That's interesting to know about "simply-reactive"

I had a similar but different issue with the other package I'm using, and I import it async in onMount:

```svelte
onMount(async () => {
	await import('dino-color-picker');
	colorPicker = document.querySelector('dino-color-picker');
});
```

I also went on the svelte discord and tried
```
{#await import('svelte-carousel') then { default: Carousel }}
	<svelte:component this={Carousel}>
```
```
	</svelte:component>
{/await}
```

**Comment by vadimkorr** [comment]
Also check out these steps https://github.com/vadimkorr/svelte-carousel#sveltekit-support

**Comment by justingolden21** [comment]
I tried following the advice on this article https://www.akashmittal.com/dynamically-import-components-svelte/

```
let Carousel;
onMount(async () => {
	await import('dino-color-picker');
	import('svelte-carousel').then((res) => (Carousel = res.default));
});
```

```
<svelte:component this={Carousel}>
	<p>hi</p>
	<p>hi</p>
	<p>hi</p>
</svelte:component>
```

and the page finally loads without error, but nothing displays

**Comment by justingolden21** [comment]
> Also check out these steps https://github.com/vadimkorr/svelte-carousel#sveltekit-support

The page loads but I get

`Uncaught TypeError: Cannot read properties of undefined (reading 'goToNext')`

when clicking the next button and none of the slides show up.

But this makes sense to me since `carousel` is never instantiated in that code, only `Carousel`

**Comment by raafirivero** [comment]
This plugin was working fine for me in Svelte, but I refactored my project for SvelteKit and am getting a similar issue. I followed the SvelteKit instructions on the Readme but I get this error in the console `Unhandled Promise Rejection: SyntaxError: Importing binding name 'default' cannot be resolved by star export entries.` – which traces back to this line of code: `const module = await import('svelte-carousel');`

My linting program says `Could not find a declaration file for module 'svelte-carousel'. `

**Comment by justingolden21** [comment]
@vadimkorr is there any fix for this? Still unable to use svelte-carousel in my project without everything crashing. Been on this for days.

**Comment by vadimkorr** [comment]
@justingolden21 , please check `svelte-carousel@1.0.17-rc3`

**Comment by justingolden21** [comment]
Thank you for the reply.

II updated from `rc1` to `rc3` but I still get

```cmd
3:11:37 PM [vite] Error when evaluating SSR module /node_modules/lodash.get/index.js?v=7699aebd:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=7699aebd:931:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-fcec4469.js:67776:15)
3:11:37 PM [vite] Error when evaluating SSR module /node_modules/simply-reactive/src/simply-reactive.js:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=7699aebd:929:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-fcec4469.js:67776:15)
3:11:37 PM [vite] Error when evaluating SSR module /node_modules/simply-reactive/main.js?v=7699aebd:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=7699aebd:927:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-fcec4469.js:67776:15)
3:11:37 PM [vite] Error when evaluating SSR module /node_modules/svelte-carousel/src/components/Carousel/createCarousel.js:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=7699aebd:925:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-fcec4469.js:67776:15)
3:11:37 PM [vite] Error when evaluating SSR module /node_modules/svelte-carousel/src/components/Carousel/Carousel.svelte:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=7699aebd:923:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-fcec4469.js:67776:15)
3:11:37 PM [vite] Error when evaluating SSR module /node_modules/svelte-carousel/src/main.js?v=7699aebd:
ReferenceError: module is not defined
    at /node_modules/lodash.get/index.js?v=7699aebd:921:1
    at instantiateModule (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\vite\dist\node\chunks\dep-fcec4469.js:67776:15)
```

In terminal, and in console on front end I get:

`Uncaught (in promise) SyntaxError: The requested module '/node_modules/lodash.isequal/index.js?v=7699aebd' does not provide an export named 'default'`

**Comment by vadimkorr** [comment]
Check this out:
1. Install: `svelte-carousel@1.0.17-rc4`
2. and follow the instructions: https://github.com/vadimkorr/svelte-carousel#vite-support

**Comment by raafirivero** [comment]
Hey – thanks for working on this over a holiday. I installed the new rc patch, updated all of the lodash dependencies (which were also throwing errors), followed the instructions on the Readme, and I'm now getting the following error: 

> ResizeObserver is not defined
ReferenceError: ResizeObserver is not defined
    at Module.createResizeObserver (/node_modules/svelte-carousel/src/utils/page.js:173:3)

For reference, the carousel works great in regular Svelte, I just can't get it working on my dev site for SvelteKit. You can see the plugin in action in regular Svelte here: [https://www.nbaboxscores.com](url). I'm porting that site to SvelteKit so I can get routing and additional features, which is why I'm interested in figuring this out.

**Comment by vadimkorr** [comment]
Seems carousel is rendered on server side in your case. For svelte kit you have to use this approach: https://github.com/vadimkorr/svelte-carousel#sveltekit-support

**Comment by raafirivero** [comment]
I followed the SvelteKit instructions. The line where the script fails is inside my onMount function where I get an error `Importing binding name default' cannot be resolved by star export entries.`

the line in the source where it fails is this: `const module = await import('svelte-carousel');`

**Comment by nnic** [comment]
I managed to get it working in SvelteKit. If you add the following property to the `kit` object in the svelte.config.js:

`vite: { optimizeDeps: { include: ['lodash.get', 'lodash.isequal', 'lodash.clonedeep'] } }`

I was getting the lodash default import error before that.

**Comment by raafirivero** [comment]
@nnic Thank you. This worked for me. I'd previously tried those same lodash configs in a separate Vite config file but I guess they weren't being included. Carousel works great now :)

**Comment by vadimkorr** [comment]
Thank you folks! Merged the readme update. Closing.
