### ISSUE TITLE
Button becomes un-clickable on scrolling to next page

### ISSUE THREAD

**Issue by eni9889** [vadimkorr/svelte-carousel#91]
I have the following sandbox: https://codesandbox.io/s/svelte-typescript-forked-l0d9f?file=/src/App.svelte:379-392

As you can see when you click on the first `one` button there is a log message but clicking on the second `one` button nothing happens.

**Comment by Albermonte** [comment]
Same here, but only happening on mobile. No button inside the carousel can be pressed.
Removing swiping and pauseOnFocus did nothing

**Comment by Juliapp** [comment]
Any resolutions to this problem? I'm facing the same but just in mobile or mobile mode in the browser

**Comment by fnavarijo** [comment]
Hello everyone.
I also have the same issue, only for mobile and mobile mode in the browser.
Playing a little bit with the source code, I was able to find that the responsible is this line: https://github.com/vadimkorr/svelte-carousel/blob/67c227995b439046c0346a8935e594927b0801ae/src/actions/swipeable/swipeable.js#L73

The `handleUp` is being called by the event added on `handleDown` function on the same file. Is there any reason why the `event.preventDefault()` was added there?

**Comment by eni9889** [comment]
Still having this same issue on mobile only

**Comment by CoryParsnipson** [comment]
I made the change that @fnavarijo suggested and saw that everything seemed to work as expected after that. I opened a pull request to remove the lines.

I am trying to come up with a workaround in the meantime, but I don't think I have enough experience. I wonder if there is a way to add a new event listener that intercepts clicks to the carousel particles and calls the right event listener?

**Comment by vadimkorr** [comment]
Released in 1.0.20
