### ISSUE TITLE
svelte-carousel don't appear to be written in CJS

### ISSUE THREAD

**Issue by lbk2knewlifegithub** [vadimkorr/svelte-carousel#95]
![image](https://user-images.githubusercontent.com/78838140/153819678-db3ed20a-ec08-42d5-a4fe-bac0295d73c4.png)

I use SvelteKit and Typescript

**Comment by yndotdev** [comment]
Facing the same error, currently.

**Comment by aditiakusuma** [comment]
same here

**Comment by OClement** [comment]
@yndotdev & @aditiakusuma 

See comments here: https://github.com/vadimkorr/svelte-carousel/issues/27

**Comment by Tal500** [comment]
Just add "type": "module" to `package.json`

**Comment by balkhalz** [comment]
> @yndotdev & @aditiakusuma
> 
> See comments here: #27

While this works, it would be great if the issue was resolved.

**Comment by Tal500** [comment]
> adding `"type": "module",` to package.json seems to indicate that this is a viable fix. although the component did run fine for me even without it.

It's a matter of how modern your environment is, the more modern the stricter it is.

**Comment by vadimkorr** [comment]
Should be fixed in https://github.com/vadimkorr/svelte-carousel/pull/126
