### ISSUE TITLE
REPL throws: `Cannot find package simply-reactive@latest`

### ISSUE THREAD

**Issue by inspiredlabs** [vadimkorr/svelte-carousel#98]
While looking at various carousels I noticed this [REPL](https://svelte.dev/repl/f503a458832f4a358d9ec00f88945ff5?version=3.46.4) throws: `Cannot find package simply-reactive@latest`.

**Comment by vadimkorr** [comment]
Duplicates https://github.com/vadimkorr/svelte-carousel/issues/118
